version: '2'
services:
  web:
    image: atlassian/confluence:7.13.6
    ports:
      - "8090:8090"
    depends_on:
      - database
  database:
    image: postgres:12.8-alpine
    environment:
    - POSTGRES_PASSWORD=root
    - POSTGRES_DB=confluence
